### ISSUE TITLE
InvalidBucketNameError2: Invalid bucket name: undefined

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/mcwzh-meme-web-builder-server-ts#7]
```
InvalidBucketNameError2: Invalid bucket name: undefined
    at Client2.putObject (/code/node_modules/minio/dist/main/minio.js:1378:15)
    at null.<anonymous> (/code/node_modules/minio/dist/main/helpers.js:85:10)
    at new Promise (<anonymous>)
    at Client2.<anonymous> (/code/node_modules/minio/dist/main/helpers.js:78:12)
    at <anonymous> (/code/src/index.ts:104:20)
    at <anonymous> (/code/src/index.ts:47:5)
    at null.cors2 (/code/node_modules/@koa/cors/index.js:98:16)
```

**Comment by XxLittleCxX** [comment]
outdated
